package org.pragmatica.aether.agent.message;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Represents a recommendation generated by the AI agent based on system analysis.
 * Contains actionable advice, suggested commands, and supporting evidence to help
 * operators understand and act on system conditions.
 * 
 * Recommendations are the primary output of the agent's analysis pipeline and
 * represent the culmination of pattern matching, predictive modeling, and LLM reasoning.
 */
public record AgentRecommendation(
    String messageId,
    long timestamp,
    MessagePriority priority,
    String analysisId,
    RecommendationType recommendationType,
    String summary,
    String rationale,
    double confidence,
    List<ActionStep> actionSteps,
    Map<String, Object> supportingEvidence,
    Duration expectedImpactTime,
    List<String> affectedComponents,
    RiskLevel riskLevel
) implements AgentMessage {
    
    /**
     * Creates a new agent recommendation with generated message ID and current timestamp.
     */
    public static AgentRecommendation create(
        String analysisId,
        RecommendationType recommendationType,
        String summary,
        String rationale,
        double confidence,
        List<ActionStep> actionSteps,
        Map<String, Object> supportingEvidence,
        Duration expectedImpactTime,
        List<String> affectedComponents,
        RiskLevel riskLevel
    ) {
        // Map risk level to message priority
        MessagePriority priority = switch (riskLevel) {
            case CRITICAL -> MessagePriority.CRITICAL;
            case HIGH -> MessagePriority.HIGH;
            case MEDIUM -> MessagePriority.NORMAL;
            case LOW -> MessagePriority.LOW;
        };
        
        return new AgentRecommendation(
            UUID.randomUUID().toString(),
            System.currentTimeMillis(),
            priority,
            analysisId,
            recommendationType,
            summary,
            rationale,
            confidence,
            actionSteps,
            supportingEvidence,
            expectedImpactTime,
            affectedComponents,
            riskLevel
        );
    }
    
    /**
     * Categories of recommendations that the agent can generate.
     */
    public enum RecommendationType {
        /** Scale slice replicas up or down */
        SCALING_RECOMMENDATION,
        /** Adjust resource allocation (CPU, memory) */
        RESOURCE_ADJUSTMENT,
        /** Optimize configuration parameters */
        CONFIGURATION_OPTIMIZATION,
        /** Restart or redeploy components */
        RESTART_RECOMMENDATION,
        /** Investigate performance issues */
        INVESTIGATION_REQUIRED,
        /** Preventive maintenance actions */
        PREVENTIVE_MAINTENANCE,
        /** Emergency response actions */
        EMERGENCY_ACTION,
        /** Capacity planning recommendations */
        CAPACITY_PLANNING,
        /** Security-related actions */
        SECURITY_ACTION,
        /** General operational advice */
        OPERATIONAL_GUIDANCE
    }
    
    /**
     * Risk levels associated with implementing the recommendation.
     */
    public enum RiskLevel {
        /** High risk of service disruption or data loss */
        CRITICAL,
        /** Moderate risk, requires careful consideration */
        HIGH,
        /** Low risk, standard operational changes */
        MEDIUM,
        /** Minimal risk, safe to execute */
        LOW
    }
    
    /**
     * Represents a single actionable step within a recommendation.
     */
    public record ActionStep(
        int stepNumber,
        String description,
        ActionType actionType,
        String command,
        Map<String, String> parameters,
        Duration estimatedDuration,
        List<String> prerequisites,
        String rollbackProcedure
    ) {
        
        /**
         * Types of actions that can be recommended.
         */
        public enum ActionType {
            /** Execute a command (scaling, restart, etc.) */
            COMMAND_EXECUTION,
            /** Update configuration values */
            CONFIGURATION_UPDATE,
            /** Monitor specific metrics */
            MONITORING_SETUP,
            /** Manual investigation or review */
            MANUAL_INVESTIGATION,
            /** Wait for specified condition */
            WAIT_CONDITION,
            /** Validate results of previous steps */
            VALIDATION_CHECK
        }
    }
    
    /**
     * Checks if this recommendation requires immediate action.
     */
    public boolean requiresImmediateAction() {
        return recommendationType == RecommendationType.EMERGENCY_ACTION ||
               riskLevel == RiskLevel.CRITICAL;
    }
    
    /**
     * Checks if this recommendation can be executed automatically.
     */
    public boolean canBeAutomated() {
        return confidence >= 0.8 && 
               riskLevel != RiskLevel.CRITICAL &&
               actionSteps.stream().allMatch(step -> 
                   step.actionType() == ActionStep.ActionType.COMMAND_EXECUTION ||
                   step.actionType() == ActionStep.ActionType.CONFIGURATION_UPDATE
               );
    }
    
    /**
     * Gets the total estimated time to complete all action steps.
     */
    public Duration getTotalEstimatedDuration() {
        return actionSteps.stream()
            .map(ActionStep::estimatedDuration)
            .reduce(Duration.ZERO, Duration::plus);
    }
    
    /**
     * Checks if this recommendation is still relevant based on its age.
     */
    public boolean isStillRelevant(Duration maxAge) {
        Duration age = Duration.ofMillis(System.currentTimeMillis() - timestamp);
        return age.compareTo(maxAge) <= 0;
    }
    
    /**
     * Creates a human-readable summary of this recommendation.
     */
    public String getDisplaySummary() {
        return String.format("[%s] %s (Confidence: %.1f%%, Risk: %s)", 
            recommendationType, summary, confidence * 100, riskLevel);
    }
}