package org.pragmatica.aether.http.handler;

import org.pragmatica.aether.slice.SliceInvokerFacade;

/**
 * Factory for creating HTTP request handlers.
 * <p>
 * Generated by annotation processor from slice route configuration.
 * Takes SliceInvokerFacade to enable cross-node request routing.
 */
public interface HttpRequestHandlerFactory {
    /**
     * Create an HTTP request handler with the given slice invoker.
     *
     * @param invoker the slice invoker for cross-node calls
     * @return configured HTTP request handler
     */
    HttpRequestHandler create(SliceInvokerFacade invoker);
}
