package org.pragmatica.aether.config;

import org.pragmatica.lang.Option;

import static org.pragmatica.lang.Option.none;
import static org.pragmatica.lang.Option.some;

/**
 * Root configuration for Aether cluster.
 *
 * <p>This is the unified configuration used by all Aether tools:
 * <ul>
 *   <li>aether-up: Reads config to generate deployment artifacts</li>
 *   <li>AetherNode: Reads config at runtime</li>
 *   <li>AetherCli: Reads connection info from config</li>
 * </ul>
 *
 * <p>Example aether.toml:
 * <pre>
 * [cluster]
 * environment = "docker"
 * nodes = 5
 * tls = false
 *
 * [cluster.ports]
 * management = 8080
 * cluster = 8090
 *
 * [node]
 * heap = "512m"
 * gc = "zgc"
 * </pre>
 *
 * @param cluster    Cluster-level configuration
 * @param node       Per-node configuration
 * @param tls        TLS configuration (when cluster.tls = true)
 * @param docker     Docker-specific settings
 * @param kubernetes Kubernetes-specific settings
 * @param ttm        TTM (Tiny Time Mixers) predictive scaling configuration
 * @param slice      Slice loading and repository configuration
 * @param appHttp    Application HTTP server configuration
 */
public record AetherConfig(ClusterConfig cluster,
                           NodeConfig node,
                           Option<TlsConfig> tls,
                           Option<DockerConfig> docker,
                           Option<KubernetesConfig> kubernetes,
                           TTMConfig ttm,
                           SliceConfig slice,
                           AppHttpConfig appHttp) {
    /**
     * Create configuration with defaults for specified environment.
     */
    public static AetherConfig forEnvironment(Environment env) {
        return new AetherConfig(ClusterConfig.forEnvironment(env),
                                NodeConfig.forEnvironment(env),
                                env.defaultTls()
                                ? some(TlsConfig.autoGenerated())
                                : none(),
                                env == Environment.DOCKER
                                ? some(DockerConfig.defaults())
                                : none(),
                                env == Environment.KUBERNETES
                                ? some(KubernetesConfig.defaults())
                                : none(),
                                TTMConfig.disabled(),
                                SliceConfig.defaults(),
                                AppHttpConfig.defaults());
    }

    /**
     * Create default configuration (Docker environment).
     */
    public static AetherConfig defaults() {
        return forEnvironment(Environment.DOCKER);
    }

    /**
     * Get the environment from cluster config.
     */
    public Environment environment() {
        return cluster.environment();
    }

    /**
     * Check if TLS is enabled.
     */
    public boolean tlsEnabled() {
        return cluster.tls();
    }

    /**
     * Builder for fluent configuration.
     */
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private Environment environment = Environment.DOCKER;
        private Integer nodes;
        private Boolean tls;
        private String heap;
        private String gc;
        private PortsConfig ports;
        private TlsConfig tlsConfig;
        private DockerConfig dockerConfig;
        private KubernetesConfig kubernetesConfig;
        private TTMConfig ttmConfig;
        private SliceConfig sliceConfig;
        private AppHttpConfig appHttpConfig;

        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        public Builder nodes(int nodes) {
            this.nodes = nodes;
            return this;
        }

        public Builder tls(boolean tls) {
            this.tls = tls;
            return this;
        }

        public Builder heap(String heap) {
            this.heap = heap;
            return this;
        }

        public Builder gc(String gc) {
            this.gc = gc;
            return this;
        }

        public Builder ports(PortsConfig ports) {
            this.ports = ports;
            return this;
        }

        public Builder tlsConfig(TlsConfig tlsConfig) {
            this.tlsConfig = tlsConfig;
            return this;
        }

        public Builder dockerConfig(DockerConfig dockerConfig) {
            this.dockerConfig = dockerConfig;
            return this;
        }

        public Builder kubernetesConfig(KubernetesConfig kubernetesConfig) {
            this.kubernetesConfig = kubernetesConfig;
            return this;
        }

        public Builder ttm(TTMConfig ttmConfig) {
            this.ttmConfig = ttmConfig;
            return this;
        }

        public Builder sliceConfig(SliceConfig sliceConfig) {
            this.sliceConfig = sliceConfig;
            return this;
        }

        public Builder appHttp(AppHttpConfig appHttpConfig) {
            this.appHttpConfig = appHttpConfig;
            return this;
        }

        public AetherConfig build() {
            // Start with environment defaults
            var base = AetherConfig.forEnvironment(environment);
            // Apply overrides
            var clusterConfig = base.cluster();
            if (nodes != null) {
                clusterConfig = clusterConfig.withNodes(nodes);
            }
            if (tls != null) {
                clusterConfig = clusterConfig.withTls(tls);
            }
            if (ports != null) {
                clusterConfig = clusterConfig.withPorts(ports);
            }
            var nodeConfig = base.node();
            if (heap != null) {
                nodeConfig = nodeConfig.withHeap(heap);
            }
            if (gc != null) {
                nodeConfig = nodeConfig.withGc(gc);
            }
            Option<TlsConfig> finalTls = tlsConfig != null
                                         ? some(tlsConfig)
                                         : (clusterConfig.tls()
                                            ? some(TlsConfig.autoGenerated())
                                            : none());
            Option<DockerConfig> finalDocker = dockerConfig != null
                                               ? some(dockerConfig)
                                               : (environment == Environment.DOCKER
                                                  ? some(DockerConfig.defaults())
                                                  : none());
            Option<KubernetesConfig> finalK8s = kubernetesConfig != null
                                                ? some(kubernetesConfig)
                                                : (environment == Environment.KUBERNETES
                                                   ? some(KubernetesConfig.defaults())
                                                   : none());
            var finalTtm = ttmConfig != null
                           ? ttmConfig
                           : TTMConfig.disabled();
            var finalSlice = sliceConfig != null
                             ? sliceConfig
                             : SliceConfig.defaults();
            var finalAppHttp = appHttpConfig != null
                               ? appHttpConfig
                               : AppHttpConfig.defaults();
            return new AetherConfig(clusterConfig,
                                    nodeConfig,
                                    finalTls,
                                    finalDocker,
                                    finalK8s,
                                    finalTtm,
                                    finalSlice,
                                    finalAppHttp);
        }
    }
}
