package org.pragmatica.aether.config;

import java.nio.file.Path;
import java.util.Optional;

/**
 * TLS configuration for secure cluster communication.
 *
 * @param autoGenerate Generate self-signed certificates if true
 * @param certPath     Path to certificate file (if not auto-generating)
 * @param keyPath      Path to private key file (if not auto-generating)
 * @param caPath       Path to CA certificate file (if not auto-generating)
 */
public record TlsConfig(
 boolean autoGenerate,
 String certPath,
 String keyPath,
 String caPath) {
    /**
     * Default: auto-generate self-signed certificates.
     */
    public static TlsConfig autoGenerated() {
        return new TlsConfig(true, "", "", "");
    }

    /**
     * Use provided certificates.
     */
    public static TlsConfig withCertificates(String certPath, String keyPath, String caPath) {
        return new TlsConfig(false, certPath, keyPath, caPath);
    }

    /**
     * Check if using user-provided certificates.
     */
    public boolean hasProvidedCertificates() {
        return !autoGenerate && !certPath.isBlank() && !keyPath.isBlank();
    }

    public Optional<Path> certFile() {
        return certPath.isBlank()
               ? Optional.empty()
               : Optional.of(Path.of(certPath));
    }

    public Optional<Path> keyFile() {
        return keyPath.isBlank()
               ? Optional.empty()
               : Optional.of(Path.of(keyPath));
    }

    public Optional<Path> caFile() {
        return caPath.isBlank()
               ? Optional.empty()
               : Optional.of(Path.of(caPath));
    }
}
